# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\example\python\qt\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_widget = QtWidgets.QWidget(self.centralwidget)
        self.plot_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.plot_widget.setObjectName("plot_widget")
        self.gridLayout.addWidget(self.plot_widget, 0, 0, 1, 1)
        self.buttons_widget = QtWidgets.QWidget(self.centralwidget)
        self.buttons_widget.setObjectName("buttons_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons_widget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connect_btn = QtWidgets.QPushButton(self.buttons_widget)
        self.connect_btn.setObjectName("connect_btn")
        self.verticalLayout.addWidget(self.connect_btn)
        self.xml_connect = QtWidgets.QPushButton(self.buttons_widget)
        self.xml_connect.setObjectName("xml_connect")
        self.verticalLayout.addWidget(self.xml_connect)
        self.disconnect_btn = QtWidgets.QPushButton(self.buttons_widget)
        self.disconnect_btn.setObjectName("disconnect_btn")
        self.verticalLayout.addWidget(self.disconnect_btn)
        self.read_btn = QtWidgets.QPushButton(self.buttons_widget)
        self.read_btn.setObjectName("read_btn")
        self.verticalLayout.addWidget(self.read_btn)
        self.broadcastRead = QtWidgets.QPushButton(self.buttons_widget)
        self.broadcastRead.setObjectName("broadcastRead")
        self.verticalLayout.addWidget(self.broadcastRead)
        self.stop_reading_btn = QtWidgets.QPushButton(self.buttons_widget)
        self.stop_reading_btn.setObjectName("stop_reading_btn")
        self.verticalLayout.addWidget(self.stop_reading_btn)
        self.set_exposure_btn = QtWidgets.QPushButton(self.buttons_widget)
        self.set_exposure_btn.setObjectName("set_exposure_btn")
        self.verticalLayout.addWidget(self.set_exposure_btn)
        self.frames_box = QtWidgets.QSpinBox(self.buttons_widget)
        self.frames_box.setMinimum(1)
        self.frames_box.setMaximum(999999999)
        self.frames_box.setProperty("value", 100)
        self.frames_box.setObjectName("frames_box")
        self.verticalLayout.addWidget(self.frames_box)
        self.exposure_box = QtWidgets.QSpinBox(self.buttons_widget)
        self.exposure_box.setPrefix("")
        self.exposure_box.setMinimum(700)
        self.exposure_box.setMaximum(1000000)
        self.exposure_box.setProperty("value", 100000)
        self.exposure_box.setObjectName("exposure_box")
        self.verticalLayout.addWidget(self.exposure_box)
        self.checkBox = QtWidgets.QCheckBox(self.buttons_widget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.buttons_widget, 0, 1, 1, 1)
        self.logs_widget = QtWidgets.QTextBrowser(self.centralwidget)
        self.logs_widget.setObjectName("logs_widget")
        self.gridLayout.addWidget(self.logs_widget, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_btn.setText(_translate("MainWindow", "AutoConfigConnect"))
        self.xml_connect.setText(_translate("MainWindow", "XmlConfigConnect"))
        self.disconnect_btn.setText(_translate("MainWindow", "Disconnect"))
        self.read_btn.setText(_translate("MainWindow", "Read"))
        self.broadcastRead.setText(_translate("MainWindow", "BroadcastRead"))
        self.stop_reading_btn.setText(_translate("MainWindow", "StopReading"))
        self.set_exposure_btn.setText(_translate("MainWindow", "SetExposure"))
        self.frames_box.setSuffix(_translate("MainWindow", " frames"))
        self.exposure_box.setSuffix(_translate("MainWindow", " us"))
        self.checkBox.setText(_translate("MainWindow", "Шторка"))
